#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service(){
	wmt_msg=`wmt_loader |grep "do module init: 30243"`
	if [ "$wmt_msg" != "" ]
	then
		#stp_msg1=`stp_uart_launcher -p /etc/firmware &`
		stp_uart_launcher -p /etc/firmware &
		#echo $stp_msg1
		#stp_msg=`echo $stp_msg1 |grep resp(ok)`
		#if [ "$stp_msg" != "" ]
		#then
			echo 0 >/dev/wmtWifi
			echo A >/dev/wmtWifi
			sleep 1
			ap_msg=`ifconfig ap0 |grep inet`
			echo $ap_msg >> /root/wmtd.log
			if [ "$ap_msg" != "" ]
			then
				echo "brctl addif br-lan ap0" >> /root/wmtd.log
				brctl addif br-lan ap0
				br_msg=`brctl show |grep ap0`
				if [ "$br_msg" != "" ]
				then
					echo "hostapd -dd /etc/hostapd/hostapd.conf &" >> /root/wmtd.log
					hostapd -dd /etc/hostapd/hostapd.conf &
				fi
			fi
		#fi
	fi
}
